package reddit

type SubredditListing struct {
	Kind        string `json:"kind"`
	ListingData struct {
		Modhash  string `json:"modhash"`
		Dist     int    `json:"dist"`
		Children []struct {
			Kind   string `json:"kind"`
			T5Data struct {
				UserFlairBackgroundColor   interface{}   `json:"user_flair_background_color"`
				SubmitTextHTML             interface{}   `json:"submit_text_html"`
				RestrictPosting            bool          `json:"restrict_posting"`
				UserIsBanned               interface{}   `json:"user_is_banned"`
				FreeFormReports            bool          `json:"free_form_reports"`
				WikiEnabled                bool          `json:"wiki_enabled"`
				UserIsMuted                interface{}   `json:"user_is_muted"`
				UserCanFlairInSr           interface{}   `json:"user_can_flair_in_sr"`
				DisplayName                string        `json:"display_name"`
				HeaderImg                  interface{}   `json:"header_img"`
				Title                      string        `json:"title"`
				IconSize                   interface{}   `json:"icon_size"`
				PrimaryColor               string        `json:"primary_color"`
				ActiveUserCount            interface{}   `json:"active_user_count"`
				IconImg                    string        `json:"icon_img"`
				DisplayNamePrefixed        string        `json:"display_name_prefixed"`
				AccountsActive             interface{}   `json:"accounts_active"`
				PublicTraffic              bool          `json:"public_traffic"`
				Subscribers                int           `json:"subscribers"`
				UserFlairRichtext          []interface{} `json:"user_flair_richtext"`
				VideostreamLinksCount      int           `json:"videostream_links_count"`
				Name                       string        `json:"name"`
				Quarantine                 bool          `json:"quarantine"`
				HideAds                    bool          `json:"hide_ads"`
				EmojisEnabled              bool          `json:"emojis_enabled"`
				AdvertiserCategory         string        `json:"advertiser_category"`
				PublicDescription          string        `json:"public_description"`
				CommentScoreHideMins       int           `json:"comment_score_hide_mins"`
				UserHasFavorited           interface{}   `json:"user_has_favorited"`
				UserFlairTemplateID        interface{}   `json:"user_flair_template_id"`
				CommunityIcon              string        `json:"community_icon"`
				BannerBackgroundImage      string        `json:"banner_background_image"`
				OriginalContentTagEnabled  bool          `json:"original_content_tag_enabled"`
				SubmitText                 string        `json:"submit_text"`
				DescriptionHTML            string        `json:"description_html"`
				SpoilersEnabled            bool          `json:"spoilers_enabled"`
				HeaderTitle                interface{}   `json:"header_title"`
				HeaderSize                 interface{}   `json:"header_size"`
				UserFlairPosition          string        `json:"user_flair_position"`
				AllOriginalContent         bool          `json:"all_original_content"`
				HasMenuWidget              bool          `json:"has_menu_widget"`
				IsEnrolledInNewModmail     interface{}   `json:"is_enrolled_in_new_modmail"`
				KeyColor                   string        `json:"key_color"`
				CanAssignUserFlair         bool          `json:"can_assign_user_flair"`
				Created                    float32       `json:"created"`
				Wls                        interface{}   `json:"wls"`
				ShowMediaPreview           bool          `json:"show_media_preview"`
				SubmissionType             string        `json:"submission_type"`
				UserIsSubscriber           interface{}   `json:"user_is_subscriber"`
				DisableContributorRequests bool          `json:"disable_contributor_requests"`
				AllowVideogifs             bool          `json:"allow_videogifs"`
				UserFlairType              string        `json:"user_flair_type"`
				AllowPolls                 bool          `json:"allow_polls"`
				CollapseDeletedComments    bool          `json:"collapse_deleted_comments"`
				EmojisCustomSize           interface{}   `json:"emojis_custom_size"`
				PublicDescriptionHTML      interface{}   `json:"public_description_html"`
				AllowVideos                bool          `json:"allow_videos"`
				IsCrosspostableSubreddit   bool          `json:"is_crosspostable_subreddit"`
				SuggestedCommentSort       interface{}   `json:"suggested_comment_sort"`
				CanAssignLinkFlair         bool          `json:"can_assign_link_flair"`
				AccountsActiveIsFuzzed     bool          `json:"accounts_active_is_fuzzed"`
				SubmitTextLabel            interface{}   `json:"submit_text_label"`
				LinkFlairPosition          string        `json:"link_flair_position"`
				UserSrFlairEnabled         interface{}   `json:"user_sr_flair_enabled"`
				UserFlairEnabledInSr       bool          `json:"user_flair_enabled_in_sr"`
				AllowChatPostCreation      bool          `json:"allow_chat_post_creation"`
				AllowDiscovery             bool          `json:"allow_discovery"`
				UserSrThemeEnabled         bool          `json:"user_sr_theme_enabled"`
				LinkFlairEnabled           bool          `json:"link_flair_enabled"`
				SubredditType              string        `json:"subreddit_type"`
				NotificationLevel          interface{}   `json:"notification_level"`
				BannerImg                  string        `json:"banner_img"`
				UserFlairText              interface{}   `json:"user_flair_text"`
				BannerBackgroundColor      string        `json:"banner_background_color"`
				ShowMedia                  bool          `json:"show_media"`
				ID                         string        `json:"id"`
				UserIsContributor          interface{}   `json:"user_is_contributor"`
				Over18                     bool          `json:"over18"`
				Description                string        `json:"description"`
				IsChatPostFeatureEnabled   bool          `json:"is_chat_post_feature_enabled"`
				SubmitLinkLabel            interface{}   `json:"submit_link_label"`
				UserFlairTextColor         interface{}   `json:"user_flair_text_color"`
				RestrictCommenting         bool          `json:"restrict_commenting"`
				UserFlairCSSClass          interface{}   `json:"user_flair_css_class"`
				AllowImages                bool          `json:"allow_images"`
				Lang                       string        `json:"lang"`
				WhitelistStatus            interface{}   `json:"whitelist_status"`
				URL                        string        `json:"url"`
				CreatedUtc                 float32       `json:"created_utc"`
				BannerSize                 interface{}   `json:"banner_size"`
				MobileBannerImage          string        `json:"mobile_banner_image"`
				UserIsModerator            interface{}   `json:"user_is_moderator"`
			} `json:"data"`
		} `json:"children"`
		After  string      `json:"after"`
		Before interface{} `json:"before"`
	} `json:"data"`
}
